# Generated by Django 4.2.4 on 2023-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionstoken',
            name='toYear',
            field=models.DateField(blank=True, null=True),
        ),
    ]
